#!/usr/bin/bash

# Part 3 task 5

# if there were no cmd args or the entered cmd arg was less than 1, prompt for input until valid input is given. if a valid cmd arg was entered, assign it to user_num
if [ $# -eq 0 ] || [ $1 -lt 1 ]; then
	read -p "Please enter an upper limit for your roll (>1): " user_num
	
	# checking that input is valid: if user_num is <1, while loop prompts for input until user_num is >1
	while [ $user_num -lt 1 ]; do
		read -p "Invalid input: roll upper limit must be >1. try again: " user_num
	done	

else
	user_num=$1
fi 

# creating a random number between 1 and 20: RANDOM creates rand num between 0 and 32767, so use modulo and +1 to get desired range                                      
rand_num=$(( 1 + $RANDOM % $user_num ))
echo "rolling between 1 and $user_num: you rolled a $rand_num!"
