#!/usr/bin/bash

if [[ $# == 0 ]]; then
	read -p "Enter a filename: " filename
else
	filename=$1
fi

if [[ -f $filename ]]; then
	echo "file exists"

else 
	echo "file does not exist"
	exit 
fi

# sorting and removing duplicates -> clean1
sort $filename | uniq > clean1.txt

# removing emails that dont start with a-z, 0-9
grep -P "^\w" clean1.txt > clean2.txt
echo "CLEAN2 NOW CONTAINS:"
cat clean2.txt




