#!/usr/bin/bash

printHelp() {
	echo -e "Usage: namechange -f find -r replace \"string to modify\" \n\t-f The text to find in the filename \n\t-r The replacement text for the new filename"
}

printHelp
