#!/usr/bin/bash

printHelp() {
	echo -e "Usage: namechange -f find -r replace \"string to modify\""
	echo -e "  -f The text to find in the filename" 
	echo -e "  -r The replacement text for the new filename"
}

# silent mode
# require input for f and r but not h
while getopts ":hf:r:" opt; do
	case "$opt" in
	h)
		printHelp
		exit
		;;
	f) 
		# find
		find=$OPTARG
		;;
	r)
		# replace
		replace=$OPTARG
		;;
	\?)
		# invalid arguments given
		printHelp
		exit
	esac
done
shift $(( OPTIND - 1 ))

echo "find was $find"
echo "replace was $replace"

# finding/checking filename
if [[ $# -ne 0 ]] &&  [[ -f $1 ]]; then
	filename=$1
	echo "filename was $filename"
else
	echo "User must provide valid filename."
	printHelp
	exit
fi

echo ""
echo "using sed"
# sed prints output unless -n flag is used
# can save the new filename to new vari by enclosing whole thing in parens
newname=$(echo $filename | sed -E "s/$find/$replace/g")
echo "new filename: $newname"
mv $filename $newname


