#!/usr/bin/bash

printHelp() {
	echo -e "Usage: namechange -f find -r replace \"string to modify\""
	echo -e "  -f The text to find in the filename" 
	echo -e "  -r The replacement text for the new filename"
}

while getopts ":hfr" opt; do
	case "$opt" in
	h)
		printHelp
		exit
		;;
	f) 
		#stuff
		;;
	r)
		#stuff
		;;
	\?)
		# invalid arguments given
		printHelp
		exit
	esac
done
